export const jobs = [
  {
    category: "All Jobs",
    title: "Associate Full Stack Developer",
    company: "Techolution",
    location: "Hyderabad",
    employment_type: "Full Time",
    skills: ["React", "Back End"],
    salary: "8 LPA",
    eligibility: "Not Eligible",
    application_deadline: "Feb 25, 2024, 11:59 PM",
    image_link: "https://example.com/job-opening.png",
  },
  {
    category: "All Jobs",
    title: "Senior Data Scientist",
    company: "Data Innovations Corp.",
    location: "Bangalore",
    employment_type: "Full Time",
    skills: ["Machine Learning", "Python"],
    salary: "10 LPA",
    eligibility: "Eligible",
    application_deadline: "Mar 5, 2024, 11:59 PM",
    image_link: "https://example.com/data-scientist-opening.png",
  },
  {
    category: "TAships",
    title: "Teaching Assistant - Physics",
    company: "Educational Institute",
    location: "Delhi",
    employment_type: "Part Time",
    skills: ["Physics", "Teaching"],
    salary: "4 LPA",
    eligibility: "Eligible",
    application_deadline: "Mar 12, 2024, 11:59 PM",
    image_link: "https://example.com/taship-physics-opening.png",
  },
  {
    category: "Applied",
    title: "Software Engineer",
    company: "TechSolutions Ltd.",
    location: "Mumbai",
    employment_type: "Full Time",
    skills: ["Java", "Spring"],
    salary: "9 LPA",
    eligibility: "Eligible",
    application_deadline: "Mar 8, 2024, 11:59 PM",
    image_link: "https://example.com/software-engineer-opening.png",
  },
  {
    category: "All Jobs",
    title: "Frontend Developer",
    company: "WebTech Solutions",
    location: "Noida",
    employment_type: "Full Time",
    skills: ["JavaScript", "HTML", "CSS"],
    salary: "7 LPA",
    eligibility: "Eligible",
    application_deadline: "Mar 20, 2024, 11:59 PM",
    image_link: "https://example.com/frontend-developer-opening.png",
  },
  {
    category: "TAships",
    title: "Teaching Assistant - Chemistry",
    company: "Science Academy",
    location: "Delhi",
    employment_type: "Part Time",
    skills: ["Chemistry", "Teaching"],
    salary: "CAD 30 per hour",
    eligibility: "Eligible",
    application_deadline: "Mar 15, 2024, 11:59 PM",
    image_link: "https://example.com/taship-chemistry-opening.png",
  },
  {
    category: "All Jobs",
    title: "Cybersecurity Analyst",
    company: "SecureTech Solutions",
    location: "Pune",
    employment_type: "Full Time",
    skills: ["Cybersecurity", "Network Security"],
    salary: "9 LPA",
    eligibility: "Eligible",
    application_deadline: "Mar 25, 2024, 11:59 PM",
    image_link: "https://example.com/cybersecurity-analyst-opening.png",
  },
  {
    category: "Applied",
    title: "UX/UI Designer",
    company: "Creative Designs Inc.",
    location: "Pune",
    employment_type: "Contract",
    skills: ["UI/UX Design", "Adobe Creative Suite"],
    salary: "6 LPA",
    eligibility: "Eligible",
    application_deadline: "Mar 18, 2024, 11:59 PM",
    image_link: "https://example.com/ux-ui-designer-opening.png",
  },
];
